### ISSUE TITLE
Huawei P smart 2019: translation text disappears on page switch

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#1424]
Original bug report by [@birtekbenbilmyr](https://twitter.com/birtekbenbilmyr).

Phone: https://www.gsmarena.com/huawei_p_smart_2019-9409.php
Android version: 10
Steps to reproduce:

- Download the app
- Download one or more translations
- Go to translation mode, observe that translation text is visible
- Switch/swipe to next/previous page.

<details><summary>Screenshots</summary>
<p>

![1 Translations](https://user-images.githubusercontent.com/452620/91447679-eb23bf80-e8b3-11ea-835c-26c73f1e04f8.jpg)

![2 Arabic-translation](https://user-images.githubusercontent.com/452620/91447683-ec54ec80-e8b3-11ea-94b1-4eb324e7120a.jpg)

![2 Turkish-translation](https://user-images.githubusercontent.com/452620/91447687-ec54ec80-e8b3-11ea-9267-4882c9732dec.jpg)

![3 Missing-translations](https://user-images.githubusercontent.com/452620/91447688-eced8300-e8b3-11ea-91de-307e15d342e9.jpg)

</p>
</details>

**Comment by ahmedre** [comment]
tried to debug this one today - this one is very odd - if the page contains ayat from a single sura, the translations don't show up, but if it contains verses from multiple suras, they do - not all databases, only a handful of the new ones, and only on those pages where ayat are only from a single sura.

could only repro this on a Huawei device.

**Comment by ahmedre** [comment]
ok - i re-encoded one of the databases that i was able to repro with and it fixed the problem. will in sha' Allah re-encode these databases and re-upload them which should fix the problem in sha' Allah. will close when this is done. jazakAllah khairan for reporting it!

**Comment by ozbek** [comment]
Ping @ahmedre! :)

**Comment by ahmedre** [comment]
Fixed this last night but forgot to close it - please ask your friend to update translations from within the app.
JazakumAllah khairan.

**Comment by ozbek** [comment]
They said Turkish Elmalılı Hamdi Yazır translation is still not visible.

**Comment by ahmedre** [comment]
i can repro - i'll reencode today in sha' Allah and upload - jazakumAllah khairan

**Comment by ahmedre** [comment]
fixed now - jazakumAllah khairan.

**Comment by ozbek** [comment]
Jazak Allah khair, it is fixed now.
