### ISSUE TITLE
Warsh/Qaloun 

### ISSUE THREAD

**Issue by youssefmehdi** [quran/quran_android#355]
Salam alaicom,

I would like to integrate warsh/Qaloun mushafs. 
Is there already a planned project on this ?

**Comment by g360230** [comment]
salam 3alaikum,

Is there anything new about the Qaloon integration?
Have you decided wether you are going to add it to your application or you are going to develop a separated one?
Please keep us informed if you need any help.

jazakumAllah khairan.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
nothing new... what resolution do you need to test with? the scripts for ayah detection are here: https://github.com/quran/ayah-detection. i also haven't used your new images yet. not sure what's the plan still, the problem is that i have other things i am working on (including the updated version of quran android), so this is not the highest priority right now :(

jazakAllah khairan,
walsalam 3alaikum.

**Comment by g360230** [comment]
salam 3alaikum,
We have just complete update of database for qaloon ayat selection.
Files are available on the following link.
http://khayra-oumma.com/tajwid/
Is it possible to create a new branch for the qaloon on your github repository ?

However, it would be much better if you can take into account our changes and generate only  one application which supports both qaloon and hafs. Do you have time for this ?

Next step for us would be :
 - Generate apk (quran android qaloon) and upload it into play store before Ramadan incha2ALLAH
 - Try to have latest updates everytime quran android is changed

We tried not to change the icon just the color but it would be much better if we had the .ai or .psd file or if the designer who made can do it for us.

Do you have any idea of making the same thing on iOS?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i am really sorry for the delayed reply - been super busy the past few days.

excellent work, may Allah reward you!

let me answer your questions with some questions :)

- what kind of changes are we talking about? if i remember correctly, qaloon was very similar to hafs (same number of pages, same number of verses, etc) and warsh was the difficult one to deal with because of the different ayah counts. if that's the case, is it just the images that need to change (and presumably the set of shuyookh we show?)

- can you generate 1260 images? i don't want to serve 1920 images anymore for a few reasons - one of which is that it's super slow to switch pages, we exceed the gl texture limit on some devices, and they just take up a lot more memory - so on quran android, we stopped letting users download 1920 images and max out at 1260 - here's an example: http://android.quran.com/data/width_1260/page049.png - please make sure that the height is less than 2048 to avoid the gl texture bug.

about separate app vs not separate app - i am not sure. the benefit of a separate app is it's much simpler to do (when the user opens the app, it automatically downloads qaloon images, whereas if we have qaloon as an option in quran, we either have to ask the user "which to download? hafs or qaloon?" or we have to let them download hafs and then go into settings and download qaloon). the bigger problem though is warsh (where the numbers for ayat are different, and so something like translations may no longer make sense for warsh).

i think either way, let's start out by making it a gradle "flavor" inside quran - the benefit of this is that even if we release a separate app for qaloon, every code change we do to the main app will also be available to the qaloon app - 99% of the code will be shared, minus a handful of things that will be overwritten when we're using qaloon.

insha'Allah please try to give me some details and i'm happy to help make this happen before ramadan insha'Allah!

jazakAllah khairan!
walsalam 3alaikum.

**Comment by ahmedre** [comment]
by the way, i am curious, were you able to get the ayah-detection script working?

**Comment by g360230** [comment]
Salamou 3alaykom,

Since you said a separate app is it's much simpler then let's do as a first step before Ramadan
I have just generated images and databse for the size 1260. I uploaded them on http://khayra-oumma.com/tajwid/.
Could you please create a new branch in the github for the qualoon application and upload Qaloon images/database on your server.
Is there anything missing to generate application for Qaloon version?
For aya-detection script, I used it and made some calculs by my own based on database you sent.
We intend to work on Warsh version after Ramadan incha2ALLAH.
By the way, do you have in mind any apple application that can use Qaloon images for personnalization?

Barakda allahou fik

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i agree about publishing it as a separate app - i disagree about making the code different, because then any enhancements that happen to standard quran android can't be made for qaloon also - so let's make the same code base compile both hafs and warsh.

i can do this part insha'Allah if you can tell me what's different (besides the urls for the images and database).

jazakAllah khairan,
walsalam 3alaikum.

**Comment by echiheb** [comment]
Salamou 3alaykom,
I have a scanned pdf of a official Qaloon Mushaf (from tunisian republic) 91,5 Mo  instead of 450 Mo.

*مصحف قالون -الطبعة التونسية.pdf: 91,5 Mo  :
http://www.megafileupload.com/Fq9/%D9%85%D8%B5%D8%AD%D9%81_%D9%82%D8%A7%D9%84%D9%88%D9%86_-%D8%A7%D9%84%D8%B7%D8%A8%D8%B9%D8%A9_%D8%A7%D9%84%D8%AA%D9%88%D9%86%D8%B3%D9%8A%D8%A9.compressed_Bm.pdf

*مصحف التجويد بالتفسير على الحاشية 604 صفحة: مصحف التجويد قالون.pdf (105.29 MB)
http://www.megafileupload.com/15qB/%D9%85%D8%B5%D8%AD%D9%81_%D8%A7%D9%84%D8%AA%D8%AC%D9%88%D9%8A%D8%AF_%D9%82%D8%A7%D9%84%D9%88%D9%86.pdf

*quran_Qaloon.pdf  10.22 MB: مع تلوين الإختلاف مع رواية حفص بالأحمر:
http://www.megafileupload.com/15qN/15qN/quran_Qaloon.pdf

**Comment by g360230** [comment]
Assalam Alaykom
Sorry for the late response.
We agree to have one repository for Qaloon and Hafs version. Is it possible to make this change and generate and publish apk before this Ramadan?

Baraka ALLAH fik
Assalam ALaykom

**Comment by ahmedre** [comment]
wa3laikum alsalam -
yes insha'Allah, i think we can finish before ramadan.
i'll work on getting something working shortly and will update the ticket.
by the way, could you run your images through some sort of compression? the zip file for 1260 images is 296 mb, whereas ours is 101 mb.

i'll go ahead and compress 1260 by hand though and upload it to the servers so we can have something to test with insha'Allah.

will update insha'Allah hopefully by tomorrow.
walsalam 3alaikum.

**Comment by g360230** [comment]
We tried to compress it but this is the max we could. Because of colors, it is very hard to get a smaller size.
Baraka ALLAH fik for the work you will do incha2ALLAH.
incha2ALLAh it will be available before Ramadan.

**Comment by ahmedre** [comment]
i managed to compress it down to 101 mb for 1260 images by just reducing the colors down to a fewer set of colors. the images look nearly the same, but there are very minor color differences that, in my opinion, make it worth the 200 mb difference.

will insha'Allah upload these images along with the code changes hopefully tomorrow insha'Allah.

**Comment by g360230** [comment]
can we have a photo ?

**Comment by ahmedre** [comment]
salam 3alaikum,
the photos for 1260 are here:
http://android.quran.com/data/qaloon/width_1260/page001.png
i've also uploaded the zip file with the same compression.

i've also updated the Quran code to be able to build Qaloon as a separate app and i made sure things work - note that right now, it will only work on a device where the largest dimension is > 1280 px (since i only uploaded the 1280 images - i still need to compress the other images before uploading them).

you can build the qaloon app by doing `./gradlew assembleQaloonDebug`. i think the only thing left is for me to remove the reciters list from there (ideally, if we can have at least one reciter, would be great - so will see if that's possible insha'Allah).

will update when so.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
btw, is anything else left besides the reciters and compressing the remaining data?

**Comment by ahmedre** [comment]
width 1024 also uploaded now - http://android.quran.com/data/qaloon/width_1024/page001.png. with this, we got the most popular sizes - will try to deal with the other sizes as well insha'Allah (800, 512, 480, and 320). al7amdulillah, we won't need 1920 nor 1280, since we now cap the images for new installations to 1260.

**Comment by g360230** [comment]
Assalam Alaykom
Baraka ALLAH fik for work done.
These are links for Qaloon riwaya reciters
أحمد خضر الطرابلسي
http://tvquranserver.com/download/tvQuran.com__AttarabolsiZip/tvQuran.com__Attarabolsi.zip
الدوكالي محمد العالم
http://tvquranserver.com/download/TvQuran.com__DoukkaliZip/TvQuran.com__Doukkali.zip
محمد الحضيري
http://tvquranserver.com/download/tvQuran.com__ElhodairiZip/tvQuran.com__Elhodairi.zip
محمد أيوب الركباوي
https://archive.org/details/Islamic_Tape-33_uP_bY_mUSLEm
This is a dropbox link for logo:
https://www.dropbox.com/s/3cszq36g8uw44u2/icon.png?dl=0
We need to update credits by adding :
Images are used with permission of NOUS MEMES EDITION ET DIFFUSION(Tunisia)

**Comment by ahmedre** [comment]
wa3laikum alsalam -
these qria2at are unlikely to work because we need timing files for them... unfortunately also, the site we usually get recitations from doesn't have any qaloon recitations (though it has 3 warsh ones).
walsalam 3alaikum.

**Comment by g360230** [comment]
Assalam Alaykom
We would rather disable this feature for this version. We will be working on timing files incha2ALLAH after that.

**Comment by ahmedre** [comment]
- the rest of the images are all uploaded (320, 480, tablet 1024 with 512).
- i like the icon (updated it in github) - can you give me one that's 512x512? i can give you a 512x512 version of quran android's if that would help (it will be needed for the google play page).

about the audio, let's wait a little bit - i've sent to a friend and will ask him if he can at least convert the Huthayfi Qaloon recitation on quranicaudio for us (http://quranicaudio.com/quran/114) - if he can, then insha'Allah we can ship with it (which is better than turning off audio) - if not, we'll disable audio until you can add some after ramadan insha'Allah.

for credits, i've updated the README and to the app credits (right now, for both apps, until insha'Allah i get a chance and redo the about screen, in which case we'll move that piece to the qaloon app only).

do you think we should change the application name that shows up in the launcher to "Quran - Qaloon" - do you think this is necessary or is "Quran" enough since most people will likely only have one of the two apps installed?

jazakAllah khairan.
walsalam 3alaikum.

**Comment by g360230** [comment]
Assalam Alaykom,
This is a dropbox link for icons with size (512x512 and 192x192)
https://www.dropbox.com/s/jcw1jtvuzskdcoa/quran_android_192x192.png?dl=0
https://www.dropbox.com/s/bfigv6qd1n2qruz/quran_android_512x512.png?dl=0

Can you please re-upload icon on github since the old icon was only a try? We regenerate the two icons with the same color palette.
We prefer to mention Riwaya on the name of tha application. "Quran - Qaloon" is much better.
It is ok for the Huthayfi Qaloon recitation.
Ok for the audio to be disabled in case we have not the files.
Baraka ALLAH fik.

**Comment by ATouhou** [comment]
Assalama aleykoum wa rahmatullahi wa barakatuh
Is it possible for you to make a "tajweed" version?
I have these files if it can help anything:
http://touhou.dk/quran-tajweed/Hafs-Tajweed.rar [High speed server, please do have a look :-) ) :+1: 
I think you should have made it possible to within 1 app change riwaya. Then change application structure so other settings are loaded from such.

**Comment by g360230** [comment]
Assalam Alaykom
Concerning audio conversion, is it automatically done? Do you use any software?

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh.

@g360230 
- icons: done.
- strings: adding "Quran - Qaloon" - done, but only for Arabic and English. we can add other languages as well (by copying the specific language folders from `madani` into `qaloon` and modifying `app_name` in `app_strings.xml`. please submit a patch if so.
- audio: looks unlikely that we'll be able to get it before ramadan, will think about how to best disable the audio bar for this case. i personally don't have a script, but the team who built ElMohafez does - unfortunately, it won't work for non-7afs riwayat though :( there's also someone who wrote a tool to make it easy to generate timing files that i can share if you're interested.

@ATouhou
- re: tajweed - technically, it's possible (and easy) - the main problem is that the tajweed pages generally speaking have a copyright on them, making it not ideal for us to push them out without the copyright holders' permission (unfortunately, the same applies for many of the translations we use today as well, and we're using them without permission :()

- re: 1 app vs many - i thought about this before going this route, but basically, there are a few problems:

1. the ui becomes tedious (on launch, you need to either ask which riwaya they want, or you always download the default one and let them change it in settings later).

2. we lose the ability to use APK expansion packs - i've been thinking about doing this since most new devices will use the 1260 images by default. by providing an apk expansion pack, downloading Quran can automatically download those pages as well. upgrading the pages becomes simple, and we no longer have to pay the bandwidth cost of hosting the images ourselves.

3. qaloon happens to be super simple, since the only differences are the pages (and corresponding ayahinfo database) and the audio. naskh (which insha'Allah i hope to try to get in soon) is a bit more complicated, because the number of pages is different (and where each ayah starts/ends relative to the page is different). the one warsh version i found was using kufi counting, which means that now, you can no longer even use the same translation databases (because kufi counting has 6214 verses instead of 6236 due to the fact that many ayat that are 2 ayahs in the standard madani counting are 1 in kufi counting and vice versa).

the benefits of splitting the apps are:
1. all apps can use the same code base (and get updated at the same time, since 99% of their code is common, minus the things that are specific to that flavor).
2. we keep the option of being able to use APK expansion packs in the future
3. simplicity - it's the easiest solution (least amount of work involved).

some of the things we lose, are that when, insha'Allah in the (hopefully near) future, we want to migrate to the new madani pages, we have to either make a new app called "Quran - Classic Madani" with the old pages and force everyone to use the new pages, or make a new app called "Quran - new Madani" that people who want can download.

we still have a chance to go with one app, but at this point in time, i think the simplicity reason is the main reason that drove the decision. i am happy to hear your thoughts and am willing to reconsider given strong enough arguments about it.

jazakumAllah khairan.
walsalam 3alaikum.

**Comment by ATouhou** [comment]
May Allah bless you brother . Ameen :-) 
I understand, in Sha Allah it will also gain some more exposure in the app store so more people will download it ^^ 

Why not host at google drive? It is well within the limits and free unlimited bandwidth i think?
Also they don't charge? :-) I think you should write a mail/message to the copyright holder and use it anyway it is fisabillilah, you don't charge for it. they should fear Allah!!

**Comment by g360230** [comment]
Assalam Alaykom
Baraka allahou fikom

Ok for disabling audio and providing an apk before the beginning of Ramadhan.
Could you please provide us the timing generation tool?
Regarding adding other languages, find attached a translation  proposal (patch for languages : de es fa fr in ru tr zh)
https://www.dropbox.com/s/ytltckzdzgnofz6/res_qaloon.zip?dl=0

jazakumAllah khairan.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
@ATouhou google drive - i don't think they'll allow it, and too risky if they decide to remove the file after some point in time (which they very well may do). regarding copyright, a friend of mine who works on an iOS quran app reached out and asked them, and they were against coming to any terms unfortunately (or wanted outlandish amounts of money).

@g360230 updated the strings. will insha'Allah work on disabling the audio. i plan on releasing a new version of Quran itself to fix some bugs and what not before ramadan, so insha'Allah can push both at the same time. will likely need your help also for modifying the text for the google play page as well insha'Allah, will update here later insha'Allah.

**Comment by ahmedre** [comment]
i made some additional changes today to support the naskh mus7af. while not everything is in place yet (example not all the image sets are uploaded yet, and the page by page downloads won't work right now, and long pressing won't work either because the database file doesn't exist at the moment), it maybe worth while for you to take a look and make sure i didn't break anything insha'Allah :)

jazakumAllah khairan.

**Comment by ATouhou** [comment]
You can make a (php) script on your site that provides the App with image location to use for download, so everytime you change host you don't need to change App code or push anything anywhere.
That same script could check if file directories exists on Google drive, if false gives your server files.

**Comment by ATouhou** [comment]
If you're not good at php, I can Write it for you,the change you have to make in the QuranFileConstants.Java is also quite simple to make This structure work :-) for scaling it is without a doubt the Best way to make it work. You Will just have to parse the JSON response from your own server which gives alternative file base directory

You can also add another double check in the download process so Even if php file gives bad info for some reason, if the file request returns bad/unexpected md5 hash on checking file integrity,  it re-download from your server

**Comment by g360230** [comment]
Assalam Alaykom

Regarding the text for the google play, how can i help you?
Is that "naskh mus7af" related to Qaloon version or not ? If yes Could you tell me which points should i check ? and Could you send me the apk ?

jazakumAllah khairan.

**Comment by ahmedre** [comment]
@ATouhou i understand what you're saying (am doing something similar for translations right now), but for now, will stick to this. the nice thing about your idea is that this is completely controlled server side, so we could dynamically change paths, etc depending on the devices (while keeping track of which devices get what and so on). but for now, will stick to this.

@g360230 what i mean is the text here: https://play.google.com/store/apps/details?id=com.quran.labs.androidquran - i could just use the same text and add that it's for qaloon in there if that works as well.

walsalam 3alaikum.

**Comment by g360230** [comment]
Assalam Alaykom
there is a defective image on the server, you can correct it
http://android.quran.com/data/qaloon/width_320/page566.png

jazakumAllah khairan.

**Comment by g360230** [comment]
I think it will be better to release the quloon app with the current status before ramdhan and we can use feedback to enhance and correct application bugs

jazakumAllah khairan.

**Comment by ahmedre** [comment]
i am traveling now, but i'll insha'Allah fix / update this image on Sunday. please let me know if you find any other broken pages in any of the resolutions.
jazakAllah khairan.

**Comment by ahmedre** [comment]
@g360230 al7amdulillah fixed image 566 both in the directory and in the 320 zip file.

**Comment by ahmedre** [comment]
@g360230 btw, what do you think of one of these icons instead? the brother who was working on the naskh images shared them and was hoping you'd go with the red one since your pages already have a bunch of red coloring in them (but even for the green, i sort of like this green color more than yours). thoughts?

![screen shot 2015-06-14 at 10 46 06 pm](https://cloud.githubusercontent.com/assets/47771/8153766/5fed0090-12e7-11e5-85e9-bdcd59faf1d1.png)

**Comment by g360230** [comment]
OK, so let us choose the green one for Qaloon version and incha2ALLAH we will use the red for Warsh version.

**Comment by ahmedre** [comment]
salam 3alaikum -
ramadan kareem. pushed code updates to both change the icon and to disable audio.
can try to push this later today or early tomorrow insha'Allah.
walsalam 3alaikum.

**Comment by g360230** [comment]
السلام عليكم 
رمضان مبارك 
اللهم يسر في هذه البرمجية
بركة الله في كل من ساهم فيها

**Comment by ahmedre** [comment]
salam 3alaikum -
ramadan mubarak!
pushed it al7amdulillah, i expect we'll see it insha'Allah in a few hours (for now, these links don't work, but should work soon insha'Allah once google approves it) -

qaloon: https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.qaloon
naskh: https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh

walsalam 3alaikum.

**Comment by afarra** [comment]
Masha Allah, tabarak Allah, this is amazing! Just tried them out! I think a
loot of people have been waiting for naskh (indopak), do you think it's
worth having a popup on update of main app that the other 2 versions are
available?

**Comment by g360230** [comment]
baraka allahou fikom :)

**Comment by akhedrane** [comment]
Salam,

Barak allah fikom for this great work.
i am looking for a textual database for riwayat-warsh, are there anyone has a version?

thanks

**Comment by Somaiagabr** [comment]
![screenshot_2015-07-24-04-55-54](https://cloud.githubusercontent.com/assets/2100167/9100964/a7abc796-3b95-11e5-95da-372f42bdc963.jpg)

**Comment by ahmedre** [comment]
cc @g360230

**Comment by g360230** [comment]
salamou 3alykom


Sorry for the late response
Good news, we finally cut the audio for Qaloon reciter أحمد خضر الطرابلسي. We generated a database with ayat timing. Please find it on following links :
SQL : https://www.dropbox.com/s/fmzup2e3qi72lob/Attarabolsi.sql?dl=0
DB   : https://www.dropbox.com/s/t059lhvefenve52/Attarabolsi.db?dl=0

Mp3 files are downloadable on : http://tvquranserver.com/download/tvQuran.com__Attarabolsi/[001-114].mp3
example : http://tvquranserver.com/download/tvQuran.com__Attarabolsi/114.mp3 -> for sourah 114
Sourat 46 is downloadable on : https://www.dropbox.com/s/elyceem8s5bpyks/046.mp3?dl=0

We fixed the error on ayah from Surah Al-Kahf. Please find new images on :https://www.dropbox.com/s/d9fh1a2r7ouo4h2/rerectificationimagemoshaf.zip?dl=0

We have some few questions :
 - A comment is posted (06/26/2015) about the issue #266 تفسير السعدي : Can you please look at it.
 - There is an issue concerning the download of files. Some users have to download them on every use. Did you encounted such problem?

baraka allhou fik

**Comment by ahmedre** [comment]
wa3laikum alsalam,
- good to hear from you - can i also add this sheikh to quranicaudio.com? who should i give credit to?

- will insha'Allah update to add the sheikh and fix the page.

- download issue: do you have any details about it? i've heard some people complaining but i haven't encountered it myself - if you do encounter it, can you give me more info about the device (screen size, and what actually exists in /sdcard/quran_android folder with details if possible?)

- issue #266 was about the arabic text, not the tafseer. which issue are you referring to?

jazakAllah khairan,
walsalam 3alaikum.

**Comment by g360230** [comment]
salamou 3alykom

    good to hear from you - can i also add this sheikh to quranicaudio.com? who should i give credit to? 
     ==> credits to tvquran.com

    will insha'Allah update to add the sheikh and fix the page.
    ==> good news

    download issue: do you have any details about it? i've heard some people complaining but i haven't encountered it myself - if you do encounter it, can you give me more info about the device (screen size, and what actually exists in /sdcard/quran_android folder with details if possible?)
    ==> I contacted a user who has the problem and he told me he will send details about problem when it will occur. 

    issue #266 was about the arabic text, not the tafseer. which issue are you referring to?
    ==> the issue is #299 

Baraka allhou fikom

**Comment by g360230** [comment]
we fixed some database issues 
you can download the update from 
SQL : https://www.dropbox.com/s/fmzup2e3qi72lob/Attarabolsi.sql?dl=0
DB : https://www.dropbox.com/s/t059lhvefenve52/Attarabolsi.db?dl=0

**Comment by ahmedre** [comment]
patched page 304. still needs some server work (anyone installing the app today will first get the bad page, and then will be prompted to upgrade on the next launch, which is not great).

**Comment by ahmedre** [comment]
finally added audio into qaloon al7amdulillah.

**Comment by albahr1** [comment]
السلام عليكم ،،، فيه شخص يرغب في شراء نسخة من البرنامج مفتوحة المصدر

هل ممكن ؟

**Comment by g360230** [comment]
salmaou 3alykom,

There is an error in audio data base for Attarabolsi : timings should be updated set time=206315 for sura=60 and ayah=5;

Is there any planned update for Quran Qaloon android application including Audios?

barak allahou fik

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
Will fix it insha'Allah. Yes, planning to push by the Android M release
(next week) insha'Allah, just finishing up fixing of some M compatibility
issues.
Walsalam 3alaikum

**Comment by ahmedre** [comment]
audio database updated on the server.

**Comment by g360230** [comment]
salamou 3alykom,

The download issue is due to CCleaner. No fix to be done.

baraka allahou fikom

**Comment by g360230** [comment]
Assalam Alaykom

there is a defective audio on the server (sourat 46), could you please correct it

jazakumAllah khairan.

**Comment by ahmedre** [comment]
salam 3alaikum bro,
can you check what some of these reviews are saying:

- someone said there's a mistake in sura baqarah 90 page 14.
- someone said sura hash ayah 1 needs correction.
- other people say "needs fixes in vowels, etc"

do you think these people don't understand that Qaloon is not hafs? should we clarify this in the description? are those verses correct?
walsalam 3alaikum.

**Comment by ahmedre** [comment]
fixed mp3 for surah 46.

**Comment by g360230** [comment]
Assalama Alaykom

Baraka llahou fik for surah 46.

We checked the verses that users commented on and they are OK. Other users wrote comments like that about verses that are incorrectly written. We think that they do not know differences between qira2at. 

It is mentioned in the description. Maybe we can add a sentence in the begin of the description to remind users that this a qira2a of Qaloon (If we can write with bigger fonts it would be better)
We refered in checking to quran flash site.

By the way, we are prepared files for qira2a of warsh (way of asbahani), please find them on the following URL :
https://www.dropbox.com/sh/vxgnpc92ksphhok/AAAcE9G1BdQ-3hBhv0rGBNRHa?dl=0
Actually we are fixing some issues in ayah selection (not very bad issues). 
We have also found audio files to add them : from http://www.versebyversequran.com/site/get-mp3/
 - Yassine Al jaza2iri
 - AbdulBassit AbduSsamad
 - Ibrahim aldosary

Can we have a version for Warsh qira2a  (way of asbahani) as we have done for Qaloon?

Can we close this bug and split it to 3 bugs to have each subject treated seperately. (Qaloon, Warsh)
barak allahou fik

**Comment by g360230** [comment]
Assalama Alaykom

you can download the qaloon recitation verse by verse :
 
-> of Houssari from this link 
https://archive.org/download/32kb------6236-ayah--verse-by-verse----quran-----mp3----32kb___by__alhosary---/32kb--alhosary--qaloon.zip

-> of Houdaifi from this link
https://archive.org/download/ra12465123456bieaaa2020_yahoo_23/

-> of taraboulsi from this link
https://archive.org/download/128kb--quran--ahmad--khedr--altrabolsy---by---qaloon-----6236---ayaat-----__ve/

barak allahou fik

**Comment by ahmedre** [comment]
salam 3alaikum @g360230 -
long time no talk! really sorry for forgetting to add sheikh hussary and huthayfi - i think we already released sheikh Taraboulsi - the archive link for sheikh hudhayfi is broken, can you update the link insha'Allah?

also can you add a new ticket for warsh with the data you have so we can get this pushed out insha'Allah?
walsalam 3alaikum.

**Comment by g360230** [comment]
Wa 3alykom esslam,
You can find the right link for sheikh hudhayfi here :
https://archive.org/details/3568356356835685368
or
https://archive.org/download/1246512346abieaaa2020_yahoo_23

I created a new bug to track warsh recitation integration : Warsh #629.
I copied the data Warsh on the new bug (issue 629)

**Comment by g360230** [comment]
Salmaou 3alykom

After adding the sound, you forgot to activate the play button.

![nok](https://cloud.githubusercontent.com/assets/7000968/12955409/31b5adf4-d023-11e5-8c03-1f14cc6056dd.png)
![ok](https://cloud.githubusercontent.com/assets/7000968/12955416/394a8530-d023-11e5-97a0-fc384608a6f2.png)

Can you fix this ?
Baraka allhou fik

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sad that i missed that - fixed in 9f6bee2ea941288be09700d65eb4b56a8af21cc9.
walsalam 3alaikum

**Comment by g360230** [comment]
Salamou 3alykom

Can you add the word "kaloun" in application search keyword

jazak Allahou khairan.

**Comment by ahmedre** [comment]
salam 3alaikum, any update on Warsh?

**Comment by g360230** [comment]
salamaou 3alykom

please find our answers on issue #629 warsh
https://github.com/quran/quran_android/issues/629
baraka allah fiik

**Comment by g360230** [comment]
Assalam Alaykom
We fixed issue in Tarabolsi recitation.
Please find files in link below
https://drive.google.com/drive/folders/0B9PxvANrtK1BdWlZTzNmUFZDODQ
We added recition of Al-Houdhaifi
Please find files in link below
https://drive.google.com/drive/folders/0B9PxvANrtK1BU0lRSC1sTlFEQVU
Baraka ALLAH fik
Hope we have it on store before Ramadan

**Comment by Abdullah076** [comment]
Dear brother, can you add recitation of ayman suwaid in your Quran app too? some tajweed learners recommend him for his good tajweed pronunciations. Info about him:
http://www.assabile.com/ayman-swed-345/ayman-swed.htm
His recitation in verse by verse format (gapped) is available here in zip form:
http://quran.ksu.edu.sa/ayat/?pg=patches&l=en
You may extract them and then add them in your Quran app & website in sha Allah.
jazakAllahu khairan.

**Comment by g360230** [comment]
Salamou 3alykom
The recitation of Aymen suwaid is hafs.
If you have a kaloon/warsh riecitation send it.

**Comment by Abdullah076** [comment]
Sorry but dont have that one.
but can you add hafs one in your hafs app please?

**Comment by g360230** [comment]
Salamou 3alykom
@Abdullah076 : this issue is reserved to kaloon version 
Can you create a new issue for this propose 
Baraka allahou fik

**Comment by ahmedre** [comment]
@g360230 i uploaded sheikh Hudhayfi and the updated files for sheikh Tarabolsi. one unfortunate thing is that right now, we don't have any versioning of the database (nor audio files), so there's no easy way to send people an update for those files :( anyone who re-downloads them will get the right ones though.

this is something i'll have to think about how to fix, but will take some time. in the meanwhile, i can close this ticket and if you have any new updates, lets open new tickets.

jazakAllah khairan!

**Comment by ahmedre** [comment]
@g360230 salam 3alaikum - is it possible for us to get Warsh 3an Nafe3 images (since @hmaher told that this is Warsh 3an Ashbani?) cc also @hmaher in case he can help.

jazakumAllah khairan.

**Comment by ahmedre** [comment]
closing since this is done. more discussion in #956

**Comment by ahmedlesd** [comment]
Hello everyone, I search for a QALOON QCF Documentation font, i want to create a Qaloon Quran App.
Can You Help Me :) @ahmedre @akhedrane @hmaher @afarra @Somaiagabr (Big Thanks !)

**Comment by ahmedre** [comment]
we currently show the images and are not rendering from the text - we only use the text for translations, etc. the images came from the QuranComplex website, which appears to be down at the moment.

**Comment by ahmedlesd** [comment]
ok thank you
is tehre is any update in Qaloon please tell me

**Comment by ahmedre** [comment]
the app is already done here - https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.qaloon
